### ISSUE TITLE
Switch from wxWidgets to libui

### ISSUE THREAD

**Issue by matyalatte** [matyalatte/tuw#19]
wxWidgets is a great library. It helped me a lot.
But I noticed it's not suitable for tiny projects like Simple Command Runner.
It's hard to optimize the library for size because its codes are messed up with legacy features.

So, I'm trying to use [libui](https://github.com/libui-ng/libui-ng) now.
Here is [an experimental branch](https://github.com/matyalatte/Simple-Command-Runner/tree/libui).
It still has tons of issues and lacks some features but the exe size is **under 600KB**!!!
It'll be under 700KB even if I restore all features that the released version has.

libui has more advantages.
The building workflow is very simple. Just by running meson via command line.
And easy to update external projects cause I don't need to edit wxWidgets' codes any more!!!
Also, the compilation is very fast cause it's a tiny library.

libui is still WIP and lacks some features I want.
But it'll be the best GUI libary for my project in the future.

**Comment by matyalatte** [comment]
I built the binaries from the latest commit. (e696e82054130c4bcb917e65ae2a401c2d139592)
[SimpleCommandRunner-libui-preview.zip](https://github.com/matyalatte/Simple-Command-Runner/files/12506290/SimpleCommandRunner-libui-preview.zip)

And here is the list of binary sizes and supproted architectures.
| OS | Size | Arch |
| -- | -- | -- |
| Windows | 578 KiB | x64 |
| macOS | 762 KB | x64, arm64 |
| Linux | 225 KB | x64 |

All of them are **smaller** than v0.5.1. And macOS build **supports ARM** devices!

libui still lacks some features I want, but all of them will be supported in the future.

- Tooltips (https://github.com/libui-ng/libui-ng/issues/188)
- Extension filters (https://github.com/libui-ng/libui-ng/pull/207)
- Float pickers (https://github.com/libui-ng/libui-ng/pull/206)

libui is absolutely the best GUI library for Simple Command Runner.

**Comment by cody271** [comment]
> And here is the list of binary sizes and supported architectures.
> And macOS build **supports ARM** devices!
>
 
libui was designed to be *extremely* portable. ARM is supported and tested on all platforms, not just macOS.
Unix backend works anywhere you have GTK, which is quite a few different CPU architectures and operating systems!

**Comment by cody271** [comment]
> libui still lacks some features I want, but all of them will be supported in the future.
> 

Yes I think we can get all three done fairly soon.

**Comment by matyalatte** [comment]
> ARM is supported and tested on all platforms, not just macOS.

I meant my CI workflows (and the built binaries with them) don't support ARM yet.
But yeah, I can release ARM version in the future.

**Comment by cody271** [comment]
Oh I see, that's right GitHub Actions CI is not very portable yet. CI runners are x86 only, without using QEMU [hacks](https://github.com/pguyot/arm-runner-action).

**Comment by matyalatte** [comment]
Switching to libui is done.
[Tuw-a9d999b-releases.zip](https://github.com/matyalatte/tuw/files/12839643/Tuw-a9d999b-releases.zip)

- Restored all features
- Optimized for size
- Support arm64 builds

| OS | Arch | Size |
| -- | -- | -- |
| Windows | x64 | 466 KiB |
| Windows | arm64 | 440 KiB |
| macOS | x64, arm64 | 516 KB |
| Linux | x64 | 135 KB |
| Linux | arm64 | 131 KB |
