### ISSUE TITLE
[Request]Radio Button

### ISSUE THREAD

**Issue by rcyggdra** [matyalatte/tuw#20]
can you add  Radio Button for "choice" type?
When there are fewer items, radio buttons are more intuitive than drop-down buttons
like this:
![image](https://github.com/matyalatte/Simple-Command-Runner/assets/8652464/d67f239a-11d4-4e20-93ac-13135a2c13f2)

**Comment by matyalatte** [comment]
Yes! so, I'll add a new type `"radio"` after working on the libui build (#19)
And maybe I'll work on [other controls that libui supports](https://libui-ng.github.io/libui-ng/group__data_entry.html) in the future.

**Comment by matyalatte** [comment]
Supported at [v0.6.1](https://github.com/matyalatte/tuw/releases/tag/v0.6.1).
You can see [an example](https://github.com/matyalatte/tuw/tree/main/examples/components/choices) for radio buttons.

The JSON format is the same as the `"choice"` type.
It will be radio buttons if you replace `"choice"` with `"radio"`
