### ISSUE TITLE
[Request]"text" type enhance

### ISSUE THREAD

**Issue by rcyggdra** [matyalatte/tuw#23]
Let the "text" type support value settings, do not output parameters including value when nothing is filled in.
Optional:regular expressions to limit the input characters and number,
for example: 
```
{
	"type": "text",
	"label": "text box", 
	"id": "text1",
	"value": " -t",
	"regex": "[A-Z]{1,4}"
},
```
Or you have a better idea to add a new type.

**Comment by matyalatte** [comment]
That's a good suggestion.
But I think the validators should be used to raise errors, not to remove parameters like `-t`.

So, I'll add another flag `optional` to ignore the error and to replace its value with an empty string.

Your example will be like this.
```json
"command": "my_exe %text1%",
"components": [
    {
        "type": "text",
        "label": "text box", 
        "id": "text1",
        "optional": true,
        "prefix": " -text=",
        "suffix": " -flag"
        "regex": "[A-Z]{1,4}"
    }
]
```

The command when you type `ABCD` in the text box.
```
my_exe -text=ABCD -flag
```

The command when you type `1234` in the text box.
```
my_exe
```

**Comment by matyalatte** [comment]
As a workaround, you can use [multiple definitions](https://github.com/matyalatte/tuw/tree/main/examples/other_features/multiple) for now.
I mean, you can provide another GUI that doesn't have the text box.

```json
"gui": [
    {
        "label": "With Text",
        "command": "my_exe -t %-%",
        "components": [
            {
                "type": "text",
                "label": "text box"
            }
        ]
    },
    {
        "label": "Without Text",
        "command": "my_exe",
        "components": []
    }
]
```

**Comment by matyalatte** [comment]
Supported at #48
