### ISSUE TITLE
about validator

### ISSUE THREAD

**Issue by rcyggdra** [matyalatte/tuw#40]
I set 'exist' to 'false' or 'not_ empty' to 'false',
I don't need to input values,but it still prompts me to enter a value:
```
                    "validator":
                    {
                        "exist": false,
                        "not_empty": false,
                        "regex": "[a-zA-Z0-9_]"
                    },
```

![image](https://github.com/user-attachments/assets/2c50c965-3e91-4b44-82d0-9cc95b28c388)

**Comment by matyalatte** [comment]
Thanks for the testing.
It's because the regex pattern `[a-zA-Z0-9_]` doesn't match empty strings. It requires the `*` operator like `[a-zA-Z0-9_]*`. You might also need anchors to check all characters are alphanumeric. like `^[a-zA-Z0-9_]*$`

**Comment by rcyggdra** [comment]
Oh, I see.
not_empty:false ≠ match zero

**Comment by matyalatte** [comment]
> not_empty:false ≠ match zero

yeah, false is for disabling the constraint, not for inverting it.
